
[[main]]
  name = "Live Map (Globe)"
  url = "https://globe.adsb.lol"
  weight = 10

[[main]]
  name = "Feed"
  weight = 20
  identifier = "feed"

[[main]]
  name = "Bare Metal (existing ADS-B station)"
  weight = 10
  parent = "feed"
  url = "feed/bare-metal"

[[main]]
  name = "ADSB.im Image (recommended for new stations / easy)"
  weight = 15
  parent = "feed"
  url = "feed/adsb-image"

[[main]]
  name = "Docker (recommended for new stations / advanced)"
  weight = 20
  parent = "feed"
  url = "feed/docker"

[[main]]
  name = "Open Data"
  weight = 40
  identifier = "open-data"

[[main]]
  name = "Tools"
  weight = 50
  identifier = "tools"


[[main]]
  name = "Grafana"
  url = "https://adsb.lol/stats"
  weight = 40
  parent = "tools"
  target = "_blank"

[[main]]
  name = "MLAT Feeder Map"
  url = "https://mlat.adsb.lol/"
  weight = 20
  parent = "tools"


[[main]]
  name = "API"
  url = "https://api.adsb.lol/"
  weight = 15
  parent = "open-data"

[[main]]
  name = "globe_history"
  url = "https://github.com/adsblol/globe_history"
  weight = 20
  parent = "open-data"

[[main]]
  name = "Uptime Status"
  url = "https://status.adsb.lol/"
  weight = 30
  parent = "tools"

[[main]]
  name = "Feeders Only"
  weight = 30
  identifier = "feeders-only"

[[main]]
  name = "My Map"
  url = "https://my.adsb.lol"
  weight = 10
  parent = "feeders-only"

[[main]]
  name = "re-api (experimental)"
  url = "https://re-api.adsb.lol/?circle=50,10,250"
  weight = 20
  parent = "feeders-only"

[[main]]
  name = "re-api documentation"
  url = "https://github.com/wiedehopf/readsb/blob/dev/README-json.md#--net-api-port-query-formats"
  weight = 21
  parent = "feeders-only"

[[main]]
  name = "Partners"
  weight = 60
  identifier = "partners"
  url = "partners"

[[social]]
  name = "Zulip (chat/forum)"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M22.767 3.589c0 1.209-.543 2.283-1.37 2.934l-8.034 7.174c-.149.128-.343-.078-.235-.25l2.946-5.9c.083-.165-.024-.368-.194-.368H4.452c-1.77 0-3.219-1.615-3.219-3.59C1.233 1.616 2.682 0 4.452 0h15.096c1.77-.001 3.219 1.614 3.219 3.589zM4.452 24h15.096c1.77 0 3.219-1.616 3.219-3.59c0-1.974-1.449-3.59-3.219-3.59H8.12c-.17 0-.277-.202-.194-.367l2.946-5.9c.108-.172-.086-.378-.235-.25l-8.033 7.173c-.828.65-1.37 1.725-1.37 2.934c0 1.974 1.448 3.59 3.218 3.59z\"/></svg>"
  url = "https://adsblol.zulipchat.com"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/adsblol"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "Mastodon"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 418 512\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M433 179.11c0-97.2-63.71-125.7-63.71-125.7-62.52-28.7-228.56-28.4-290.48 0 0 0-63.72 28.5-63.72 125.7 0 115.7-6.6 259.4 105.63 289.1 40.51 10.7 75.32 13 103.33 11.4 50.81-2.8 79.32-18.1 79.32-18.1l-1.7-36.9s-36.31 11.4-77.12 10.1c-40.41-1.4-83-4.4-89.63-54a102.54 102.54 0 0 1-.9-13.9c85.63 20.9 158.65 9.1 178.75 6.7 56.12-6.7 105-41.3 111.23-72.9 9.8-49.8 9-121.5 9-121.5zm-75.12 125.2h-46.63v-114.2c0-49.7-64-51.6-64 6.9v62.5h-46.33V197c0-58.5-64-56.6-64-6.9v114.2H90.19c0-122.1-5.2-147.9 18.41-175 25.9-28.9 79.82-30.8 103.83 6.1l11.6 19.5 11.6-19.5c24.11-37.1 78.12-34.8 103.83-6.1 23.71 27.3 18.4 53 18.4 175z\"></path></svg>"
  url = "https://mastodon.social/@adsblol"
  weight = 30

[[footer]]
  name = "Privacy and License"
  url = "/privacy-license/"
  weight = 10
